<h1>Försäkra enskild firma</h1>
<p>Företagsförsäkring borde vara lika självklart för företagaren som hemförsäkringen är för en privatperson. Men så är det inte. Ett stort antal företagare är oförsäkrade vilket till stor sannolikhet beror på okunskap om risken att vara detta. Här går vi igenom varför personer med enskild firma bör teckna företagsförsäkring, vad som ingår och vad detta kostar.</p>
<div class="su-button-center"><a href=" https://www.xn--fretagsfrskring-9kb01ah.com/recommends/svedea/" class="su-button su-button-style-default su-button-wide" style="color:#FFFFFF;background-color:#1c9e42;border-color:#167e35;border-radius:0px;-moz-border-radius:0px;-webkit-border-radius:0px" target="_self" rel="nofollow"><span style="color:#FFFFFF;padding:7px 20px;font-size:16px;line-height:24px;border-color:#60bb7b;border-radius:0px;-moz-border-radius:0px;-webkit-border-radius:0px;text-shadow:none;-moz-text-shadow:none;-webkit-text-shadow:none"><i class="fa fa-arrow-right" style="font-size:16px;color:#FFFFFF"></i> Teckna försäkring för enskild firma här</span></a></div>
<h2>Varför ska man försäkra enskild firma?</h2>
<p>År 2014 genomförde opinionsföretaget Novus en undersökning åt försäkringsbolaget Trygg Hansa där 481 småföretagare fick svara på om de hade en företagsförsäkring eller inte. Av dessa var det hela 30% som inte hade försäkring. Försäkringsbolaget drog slutsatsen att bristen på kunskap kring vad företagsförsäkringar egentligen ger för skydd var orsaken till att så många valde att vara oförsäkrad.</p>
<h3>Mer än bara egendom</h3>
<p>Många företagare tänker att de inte är i behov av försäkring eftersom de inte har någon värdefull egendom att försäkra. Det kan exempelvis vara IT-konsulter, författare eller andra företag som har mycket få inventarier. Felet i detta fall är att man utgår från att en företagsförsäkring framförallt är en Egendomsförsäkring. Men Egendomsförsäkring är enbart en av de många försäkringsdelar som ingår i en företagsförsäkring.</p>
<h3>Hemförsäkringen ger inget skydd</h3>
<p><img class="alignright size-medium wp-image-30" src="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/hemforsakring-300x205.jpg" alt="hemförsäkring" width="300" height="205" srcset="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/hemforsakring-300x205.jpg 300w, https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/hemforsakring.jpg 500w" sizes="(max-width: 300px) 100vw, 300px" />Andra utgår från att hemförsäkringen täcker de skador som uppkommer på företagets egendom. En del tror även att andra delar i hemförsäkringen (exempelvis Ansvar &#038; Rättsskydd) även gäller för företagsrelaterade ärenden. Felet i detta fall är att man inte ser skillnaden mellan privatperson och företag – en gräns som försäkringsbolagen tydligt drar.</p>
<p>En person som driver enskild firma och inte har försäkring riskerar alltså stora kostnader vid skador på företagets egendom. Men framförallt har man inget ekonomiskt skydd vid skadeståndskrav, rättstvister eller stora avbrott i företagets verksamhet.</p>
<h2>Innehåll i företagsförsäkringen &#8211; BAS</h2>
<p>En företagsförsäkring för enskild firma ger ett ekonomiskt skydd både för egendom inom företaget samt för personen som driver företaget. Försäkringen består alltså av flera olika försäkringsdelar så som Egendomsförsäkring. Allriskförsäkring, Rättstvist osv.</p>
<p>De allra flesta försäkringsbolag som erbjuder försäkring för enskild firma gör detta på två (eller fler) nivåer. Den lägsta nivån, som därmed även är billigast, har de försäkringsdelar som samtliga enskilda firmor har behov av för att få ett grundläggande försäkringsskydd. <strong>Exakt vilka delar som ingår kan variera mellan olika försäkringsbolag men några av de delar som mycket ofta ingår i basutbudet är:</strong><br />
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Ansvarsförsäkringen</div><div class="su-service-content su-clearfix" style="padding-left:40px">Även om du inte har något värde i inventarier i företaget så behövs en företagsförsäkring. Oavsett yrke som kan det uppkomma tillfällen då kunder, leverantörer eller andra kräver företaget på skadestånd. Skadestånd kan handla om belopp på flera miljoner och eftersom man som privatperson är ekonomisk ansvarig för sin enskilda firma blir man själv betalningsskyldig om inte försäkring finns. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Avbrotts- och extrakostnadsförsäkring</div><div class="su-service-content su-clearfix" style="padding-left:40px">Vid brand, skadegörelse eller andra större skador på egendom kan avbrott ske i företagets verksamhet ske. Avbrott som kan vara mycket kostsamma då intäkterna kraftigt minskar samtidigt som de fasta kostnaderna ändå måste betalas. Denna försäkringsdel betalar dessa kostnader under viss tid efter olyckstillfället. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Rättsskyddsförsäkring</div><div class="su-service-content su-clearfix" style="padding-left:40px">Vid en tvist (skattemål och civilmål) som dras till domstol ersätter Rättsskyddsförsäkringen juristkostnader.</div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Egendomsförsäkring</div><div class="su-service-content su-clearfix" style="padding-left:40px">Ersätter skador på, eller stöld av, egendom som ägs av företaget.</p>
<p>Utöver denna ”bas” ingår ibland ytterligare grundläggande försäkringsdelar som då inkluderas i baspaketet utifrån de behov som finns inom den bransch som företaget är verksam inom. </div></div>
<h2>Innehåll i företagsförsäkringen – Stora paketet</h2>
<p>De allra flesta försäkringsbolag skapar två olika försäkringspaket som företagarna kan välja mellan. Som nämnts ovan brukar det mindre paketet innehålla de grundläggande delarna medan det större paketet är bredare och mer utförligt.</p>
<p>Nedan nämns några av de vanligare områden som försäkringar kan tecknas inom och några försäkringar inom dessa områden. Det är exempel på försäkringar som följer med när större försäkringspaket tecknas.<br />
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Ansvar</div><div class="su-service-content su-clearfix" style="padding-left:40px"> Specifika ansvarsförsäkringar inom vissa områden, Rättsskydd, Patientansvar och Patent- och immaterialrätt. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Sjukvård och olycksfall </div><div class="su-service-content su-clearfix" style="padding-left:40px">Olycksfallsförsäkring som gäller för anställda och även ofta besökare till företaget. Avbrott vid arbetsoförmåga ger ersättning om en person inte kan utföra sina uppgifter på arbetsplatsen på grund av längre sjukskrivning. Ytterligare försäkringar är Överfallsförsäkring och Krisförsäkring. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Fordonsförsäkring</div><div class="su-service-content su-clearfix" style="padding-left:40px">Läs mer under ”Bilförsäkring för företag”. Utöver bilförsäkring finns självklart även försäkringar för andra fordon.<br />
</div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Speciell egendom</div><div class="su-service-content su-clearfix" style="padding-left:40px">Egendomsförsäkring ingår i de flesta företagsförsäkringar. Men ibland krävs speciell försäkring för enskild egendom. Exempel är Kyl- och Frysförsäkring som ger ersättning för varor som blivit obrukbara vid temperaturfall i kyl eller frys</div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Tjänsteresa och utlandsresa</div><div class="su-service-content su-clearfix" style="padding-left:40px">Olycksfallsförsäkring som gäller under tjänsteresa i Sverige och utomlands. Det finns även specifika försäkringar vid utlandsplacering, studier utomlands eller för utländska besökare. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Fastighet</div><div class="su-service-content su-clearfix" style="padding-left:40px"> Försäkring för fastigheter, skogsfastigheter m.m. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> Transport</div><div class="su-service-content su-clearfix" style="padding-left:40px">Specifika försäkringar för företag inom transportbranschen. Exempelvis GVP, lyft och utställningsförsäkring. </div></div>
<div class="su-service"><div class="su-service-title" style="padding-left:40px;min-height:26px;line-height:26px"><i class="fa fa-info" style="font-size:26px;color:#333"></i> ID-stöld</div><div class="su-service-content su-clearfix" style="padding-left:40px">I många hemförsäkringar ingår ID-skydd. Det är däremot mer ovanligt att det ingår som standard i företagsförsäkringarna. Med denna försäkring ges hjälp med att förebygga ID-stöld samt begränsa skadan om detta ändå skulle ske. </div></div>
<h2>Vilken försäkring behöver jag?</h2>
<figure id="attachment_32" style="width: 390px" class="wp-caption alignright"><img class="wp-image-32" src="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/bestamma-300x223.jpg" alt="svårt att välja företagsförsäkring" width="400" height="298" srcset="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/bestamma-300x223.jpg 300w, https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/bestamma.jpg 500w" sizes="(max-width: 400px) 100vw, 400px" /><figcaption class="wp-caption-text">Många företagare vet inte vilken försäkring man ska välja.</figcaption></figure>
<p>Många företagare upplever det svårt att veta vilket försäkringsskydd de behöver och även avgöra hos vilket försäkringsbolag försäkringen ska tecknas. För att möta företagarnas behov har försäkringsbolagen valt att skapa färdiga försäkringspaket utifrån olika branscher. Det kan exempelvis vara ett komplett paket för de som har företag inom Handel och ett annat paket för de som jobbar med IT-verksamhet.</p>
<p>I dessa paket har försäkringsbolaget lagt med de grundläggande delarna i en företagsförsäkring samt mer branschspecifika försäkringar. Därmed behöver man oftast bara ange företagets organisationsnummer för att försäkringsbolaget ska se vilken verksamhet som bedrivs och därmed vilket försäkringspaket som behövs.</p>
<p>Ändrar sig sedan behovet genom att det blir större omsättning, fler anställda eller att verksamheten breddas bör alltid försäkringsbolaget kontaktas så att försäkringen alltid är anpassad utifrån företagets behov.</p>
<p>Vilken försäkring som just ditt företag behöver kan alltså försäkringsbolaget avgöra genom att du ber om offert och där anger organisationsnummer, omsättning och antal anställda.</p>
<h2>Vad kostar det?</h2>
<p><img class="alignright wp-image-35" src="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/kostnad-300x200.jpg" alt="vad kostar det att försäkra enskild firma?" width="400" height="267" srcset="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/kostnad-300x200.jpg 300w, https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/kostnad.jpg 500w" sizes="(max-width: 400px) 100vw, 400px" />Hur mycket en företagsförsäkring för enskild firma kostar beror främst på vilken bransch som företaget är verksam inom samt företagets omsättning. En del försäkringsbolag har en enkel prispresentation på hemsidan. Du fyller då i företagets organisationsnummer (ditt personnummer) i en ruta och klickar sedan vidare för att få ett prisförslag.</p>
<p>Försäkringsbolaget utgår då från de uppgifter som finns registrerade för gällande företag. Det är därför viktigt att kontrollera att den verksamhetsbeskrivning som presenteras stämmer överens med företagets verksamhet. Det som presenteras brukar då vara en grundläggande företagsförsäkring utifrån de behov ett företag har inom den branschen.</p>
<p>Vill du välja tillägg går detta att göra online eller i kontakt med försäkringsbolaget. Faktorer som därmed påverkar priset på företagsförsäkringen är både bransch, antal anställda, omsättning och behov av tilläggsförsäkringar.</p>
<p>De billigaste företagsförsäkringarna för en enskild firma kostar någon tusenlapp per år.</p>
<h2>Bilförsäkring &#8211; Ska företaget äga bilen eller inte?</h2>
<p><img class="alignright wp-image-38" src="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/bilforsakring-300x207.jpg" alt="bilförsäkring" width="320" height="221" srcset="https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/bilforsakring-300x207.jpg 300w, https://www.xn--fretagsfrskring-9kb01ah.com/wp-content/uploads/2017/07/bilforsakring.jpg 500w" sizes="(max-width: 320px) 100vw, 320px" />Många som driver Enskild firma har behov av en bil för att kunna sälja produkter eller utföra sina tjänster. Däremot är det inte alltid självklart om företaget ska äga bilen eller inte. Har du en bil som enbart används inom företaget skrivs den allra oftast på företaget. Men det är sällan så för egenföretagare. Vad som är bäst rent ekonomiskt beror på hur mycket bilen kommer att användas samt hur mycket den kommer att användas privat.</p>
<p>Oavsett om bilen ägs privat eller om den är skriven på företaget så är det enkelt att jämföra premie på bilförsäkring online då de flesta försäkringsbolag ger offert bara man anger registreringsnummer och personnummer/organisationsnummer.</p>
<h2>Glöm inte inkomstförsäkringen</h2>
<p>Som anställd ser många det som en självklarhet att vara medlem i ett fackförbund. Därmed får man oftast en inkomstförsäkring som gör att ersättning vid arbetslöshet uppgår till 80% av lönen. (förutsatt att man även är med i A-kassa). Men de som driver eget företag är inte i lika stor utsträckning med i fackförbund och missar ofta inkomstförsäkring.</p>
<p>Inkomstförsäkring kan tecknas som en separat försäkring hos flera olika försäkringsbolag. Ett annat alternativ är att bli medlem hos någon av de fackförbund där inkomstförsäkring ingår och som vänder sig mot de med enskild firma. Ett medlemskap kan även ge rabatt och tillgång till passande försäkringar.</p>
<blockquote><p><strong>Exempel: Unionen Egenföretagare</strong></p>
<p>Som medlem i Unionen Egenföretagare ges en inkomstförsäkring som kompletterar ersättning från A-kassan så att man får 80% av tidigare lönenivå upp till 60 000 kr. Via förbundet går det även att få 20% rabatt på företagsförsäkring hos Folksam.</p></blockquote>
<h2>Har du anställda?</h2>
<p>Har du anställda är det vanligt att teckna kollektivavtal. I detta fall måste du som företagare teckna de avtalsförsäkringar som ingår i kollektivavtalet. Finns inte kollektivavtal bör du se över vad som behövs gällande olycksfallsförsäkring, sjukförsäkring, tjänstepension, livförsäkring m.m.</p>
<h2>Vanliga frågor och svar</h2>
<div class="su-spoiler su-spoiler-style-default su-spoiler-icon-plus"><div class="su-spoiler-title"><span class="su-spoiler-icon"></span>Jag driver mitt företag hemifrån. Gäller hemförsäkringen då?</div><div class="su-spoiler-content su-clearfix">Nej. Oavsett var du bedriver ditt företag så täcker inte hemförsäkringen för den egendom som tillhör företaget. Det går heller aldrig att få ersättning från hemförsäkringen vid skadeståndskrav eller vid rättstvister. Kort sagt så är all egendom och de händelser som är kopplade till företagets aktivitet inte försäkrade av hemförsäkringen. Som företagare bör man därför alltid teckna en företagsförsäkring. </div></div>
<div class="su-spoiler su-spoiler-style-default su-spoiler-icon-plus su-spoiler-closed"><div class="su-spoiler-title"><span class="su-spoiler-icon"></span>Jag har inte något av värde – behöver jag företagsförsäkring?</div><div class="su-spoiler-content su-clearfix">En företagsförsäkring består av flera olika försäkringsdelar. En av dessa är Egendomsförsäkring. Ett företag som inte har någon egendom av värde behöver inte just denna försäkringsdel. Däremot bör man alltid teckna Ansvarsförsäkring och liknande försäkringsdelar som ger ekonomisk trygghet vid skadeståndskrav och liknande. Alla företag bör ha företagsförsäkring – däremot varierar det vad denna bör ha för delar. </div></div>
<div class="su-spoiler su-spoiler-style-default su-spoiler-icon-plus su-spoiler-closed"><div class="su-spoiler-title"><span class="su-spoiler-icon"></span>Vad avgör priset på en företagsförsäkring?</div><div class="su-spoiler-content su-clearfix">För att få en offert på en företagsförsäkring från ett försäkringsbolag krävs det att man anger företagets organisationsnummer, omsättning och hur många som är anställda. Försäkringsbolaget utgår då från vilken verksamhet som bedrivs och ger offert utifrån detta. En försäkring för en enskild firma med enbart en eller ett par anställd hamnar premien sällan på mer än några tusenlappar. Men det beror självklart på om det behövs tillägg så som bilförsäkring osv. </div></div>
<h2>Kort sammanfattning – Det viktigaste att ta hänsyn till</h2>
<div class="su-list su-list-style-">
<ul>
<li><i class="fa fa-check" style="color:#238823"></i> Teckna företagsförsäkring oavsett omsättning eller verksamhet.</li>
<li><i class="fa fa-check" style="color:#238823"></i> Glöm inte inkomstförsäkring (ingår inte i företagsförsäkringen)</li>
<li><i class="fa fa-check" style="color:#238823"></i> Fundera på om bilen ska ägas privat eller i företaget.</li>
</ul>
